import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./(assets)/globals.css";
import Navbar from "./navbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 p-5`}
      >
        <div className="container mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
          <Navbar />
          <main className="p-5 bg-blue-50">
            <Suspense fallback={<div>Loading...</div>}>
                {children}
            </Suspense>
          </main>
          <footer className="py-5 text-center text-sm text-blue-500">
            Copyright &copy;2025 Zulfahmidev.
          </footer>
        </div>
      </body>
    </html>
  );
}
